figure;
hold on;

plot3(...
    MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(:,1),...
    MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(:,2),...
    MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(:,3),...
    'bo');

plot3(...
    MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(:,1),...
    MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(:,2),...
    MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(:,3),...
    'ro');

for chan = 1:length(MCP_data(1).Experiment.Probe_arrays.Geometry.Lambda):size(MCP_data(1).Experiment.Probe_arrays.Geometry.MeasList,1)
    
    det=MCP_data(1).Experiment.Probe_arrays.Geometry.MeasList(chan,2);
    src=MCP_data(1).Experiment.Probe_arrays.Geometry.MeasList(chan,1);

    plot3(...
        [MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(det,1);MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(src,1)],...
        [MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(det,2);MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(src,2)],...
        [MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(det,3);MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(src,3)],...
        'k-')
    
    
    text(...
        mean([MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(det,1);MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(src,1)]),...
        mean([MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(det,2);MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(src,2)]),...
        mean([MCP_data(1).Experiment.Probe_arrays.Geometry.DetPos(det,3);MCP_data(1).Experiment.Probe_arrays.Geometry.SrcPos(src,3)]),...
        num2str(chan));
end

hold off;